# Generated by Django 2.2.7 on 2019-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Privilege', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
