# Generated by Django 2.2.7 on 2019-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Privilege', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
