# Generated by Django 2.2.7 on 2019-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
