# Generated by Django 2.2.7 on 2019-12-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191206_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
    ]
